### ISSUE TITLE
Test output is not colored when `verbose` option is used

### ISSUE THREAD

**Issue by CIAvash** [Leont/app-prove6#7]
It is colored without `verbose`.

**Comment by sdondley** [comment]
Reporting same. On a mac. See https://www.reddit.com/r/rakulang/comments/s2dps1/colored_output_with_prove6_on_mac/

**Comment by Leont** [comment]
Just fixed that last week, will try to release it this weekend.

**Comment by Leont** [comment]
Done in TAP 0.3.3

**Comment by sdondley** [comment]
GitHub needs a one-click "buy a beer" button.

**Comment by sdondley** [comment]
crap. still not getting color with `-v` switch after upgrading `TAP::Harness`.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/2506364/150614056-d6f3bec9-a2b9-44df-b779-2a31360f49b2.png">

**Comment by Leont** [comment]
What does `prove6 -v` tell you?

**Comment by sdondley** [comment]
`prove6 0.0.12 with TAP::Harness 0.2.2 on rakudo (2021.12)`

**Comment by Leont** [comment]
Then you need to upgrade the `TAP` module

**Comment by sdondley** [comment]
Tried that with zef. Says it's up to date.

**Comment by sdondley** [comment]
Ok, by `TAP` I assumed you meant `TAP::Harness`. This worked:

```
> $ zef upgrade TAP
===> Searching for: TAP
The following distributions will be upgraded: TAP:ver<0.3.4>
===> Updating: TAP:ver<0.3.4>
===> Testing: TAP:ver<0.3.4>
===> Testing [OK] for TAP:ver<0.3.4>
===> Installing: TAP:ver<0.3.4>
```
